[2024-07-16T08:00:15.148+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T08:00:15.158+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T08:00:15.158+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-16T08:00:15.174+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2024-07-15 00:00:00+00:00
[2024-07-16T08:00:15.182+0000] {standard_task_runner.py:57} INFO - Started process 4474 to run task
[2024-07-16T08:00:15.185+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_remote_jupyter_notebook', 'run_notebook', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '1510', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmp_b_b5uio']
[2024-07-16T08:00:15.187+0000] {standard_task_runner.py:85} INFO - Job 1510: Subtask run_notebook
[2024-07-16T08:00:15.238+0000] {task_command.py:410} INFO - Running <TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-07-15T00:00:00+00:00 [running]> on host be64f240bd41
[2024-07-16T08:00:15.337+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_remote_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-16T08:00:15.416+0000] {logging_mixin.py:149} INFO - Notebook content: {
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "a9e85d21-27ab-42bb-a1df-e3760128f532",
      "metadata": {},
      "outputs": [],
      "source": [
        "print(\"Hello World!\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "a8060e2e-a775-482b-9ab6-2a26b0268ec2",
      "metadata": {},
      "outputs": [],
      "source": [
        "a = 1\n",
        "b = 2\n",
        "print(a+b)"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.11.2"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}
[2024-07-16T08:00:15.417+0000] {logging_mixin.py:149} INFO - Error processing notebook: Notebook does not appear to be JSON: ''
[2024-07-16T08:00:15.418+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/nbformat/reader.py", line 20, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/airflow/dags/run_notebook.py", line 30, in execute_remote_notebook
    nb = nbformat.read(f, as_version=4)
  File "/home/airflow/.local/lib/python3.7/site-packages/nbformat/__init__.py", line 171, in read
    return reads(buf, as_version, capture_validation_error, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/nbformat/__init__.py", line 89, in reads
    nb = reader.reads(s, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/nbformat/reader.py", line 76, in reads
    nb_dict = parse_json(s, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/nbformat/reader.py", line 26, in parse_json
    raise NotJSONError(message) from e
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/run_notebook.py", line 43, in execute_remote_notebook
    raise AirflowException(f"Failed to process Jupyter notebook: {str(e)}")
NameError: name 'AirflowException' is not defined
[2024-07-16T08:00:15.430+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=run_remote_jupyter_notebook, task_id=run_notebook, execution_date=20240715T000000, start_date=20240716T080015, end_date=20240716T080015
[2024-07-16T08:00:15.444+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1510 for task run_notebook (name 'AirflowException' is not defined; 4474)
[2024-07-16T08:00:15.478+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-16T08:00:15.498+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T08:30:34.348+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-18T08:30:34.354+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-18T08:30:34.354+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-18T08:30:34.364+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2024-07-15 00:00:00+00:00
[2024-07-18T08:30:34.370+0000] {standard_task_runner.py:57} INFO - Started process 3189 to run task
[2024-07-18T08:30:34.373+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_remote_jupyter_notebook', 'run_notebook', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '568', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmp4s64g0xk']
[2024-07-18T08:30:34.375+0000] {standard_task_runner.py:85} INFO - Job 568: Subtask run_notebook
[2024-07-18T08:30:34.410+0000] {task_command.py:410} INFO - Running <TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-07-15T00:00:00+00:00 [running]> on host e7816f9101dd
[2024-07-18T08:30:34.476+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_remote_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-18T08:30:35.967+0000] {logging_mixin.py:149} INFO - Notebook executed and updated successfully on the server.
[2024-07-18T08:30:35.968+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-07-18T08:30:35.977+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=run_remote_jupyter_notebook, task_id=run_notebook, execution_date=20240715T000000, start_date=20240718T083034, end_date=20240718T083035
[2024-07-18T08:30:36.033+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-18T08:30:36.048+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
