[2024-07-16T07:49:09.237+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-07-16T07:49:09.253+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-07-16T07:49:09.255+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-16T07:49:09.279+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2024-04-21 00:00:00+00:00
[2024-07-16T07:49:09.288+0000] {standard_task_runner.py:57} INFO - Started process 1022 to run task
[2024-07-16T07:49:09.292+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_remote_jupyter_notebook', 'run_notebook', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '1393', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmpwwjykhim']
[2024-07-16T07:49:09.294+0000] {standard_task_runner.py:85} INFO - Job 1393: Subtask run_notebook
[2024-07-16T07:49:09.345+0000] {task_command.py:410} INFO - Running <TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-21T00:00:00+00:00 [running]> on host dcbd1801a890
[2024-07-16T07:49:09.569+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_remote_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-07-16T07:49:09.571+0000] {run_notebook.py:14} INFO - Attempting to connect to http://host.docker.internal:8888/api/contents/Notebooks/notebook.ipynb?token=e8a8150423dfd35bee318800bfcf7c9191ca7485b5cb9fde
[2024-07-16T07:49:09.586+0000] {execute.py:83} INFO - Input Notebook:  /tmp/input_notebook.ipynb
[2024-07-16T07:49:09.587+0000] {execute.py:84} INFO - Output Notebook: /opt/***/outputs/output.ipynb
[2024-07-16T07:49:09.588+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/run_notebook.py", line 34, in execute_remote_notebook
    parameters=parameters
  File "/home/airflow/.local/lib/python3.7/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/home/airflow/.local/lib/python3.7/site-packages/nbformat/__init__.py", line 91, in reads
    nb = convert(nb, as_version)
  File "/home/airflow/.local/lib/python3.7/site-packages/nbformat/converter.py", line 62, in convert
    raise ValidationError(msg) from None
jsonschema.exceptions.ValidationError: Notebook could not be converted from version 1 to version 2 because it's missing a key: cells
[2024-07-16T07:49:09.596+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=run_remote_jupyter_notebook, task_id=run_notebook, execution_date=20240421T000000, start_date=20240716T074909, end_date=20240716T074909
[2024-07-16T07:49:09.606+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1393 for task run_notebook (Notebook could not be converted from version 1 to version 2 because it's missing a key: cells; 1022)
[2024-07-16T07:49:09.625+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-16T07:49:09.645+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T07:00:29.570+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-07-18T07:00:29.588+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-21T00:00:00+00:00 [queued]>
[2024-07-18T07:00:29.589+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-18T07:00:29.697+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2024-04-21 00:00:00+00:00
[2024-07-18T07:00:29.708+0000] {standard_task_runner.py:57} INFO - Started process 24582 to run task
[2024-07-18T07:00:29.714+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_remote_jupyter_notebook', 'run_notebook', 'scheduled__2024-04-21T00:00:00+00:00', '--job-id', '479', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmp8yspat1y']
[2024-07-18T07:00:29.718+0000] {standard_task_runner.py:85} INFO - Job 479: Subtask run_notebook
[2024-07-18T07:00:29.832+0000] {task_command.py:410} INFO - Running <TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-21T00:00:00+00:00 [running]> on host 6c8b3b9a6388
[2024-07-18T07:00:30.046+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_remote_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T00:00:00+00:00'
[2024-07-18T07:00:34.298+0000] {logging_mixin.py:149} INFO - Notebook executed and updated successfully on the server.
[2024-07-18T07:00:34.299+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-07-18T07:00:34.322+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=run_remote_jupyter_notebook, task_id=run_notebook, execution_date=20240421T000000, start_date=20240718T070029, end_date=20240718T070034
[2024-07-18T07:00:34.391+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-18T07:00:34.427+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
