[2024-07-16T07:54:18.771+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-26T00:00:00+00:00 [queued]>
[2024-07-16T07:54:18.787+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-26T00:00:00+00:00 [queued]>
[2024-07-16T07:54:18.787+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-16T07:54:18.813+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2024-04-26 00:00:00+00:00
[2024-07-16T07:54:18.824+0000] {standard_task_runner.py:57} INFO - Started process 2082 to run task
[2024-07-16T07:54:18.833+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_remote_jupyter_notebook', 'run_notebook', 'scheduled__2024-04-26T00:00:00+00:00', '--job-id', '1414', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmp7rb1o6lw']
[2024-07-16T07:54:18.837+0000] {standard_task_runner.py:85} INFO - Job 1414: Subtask run_notebook
[2024-07-16T07:54:18.974+0000] {task_command.py:410} INFO - Running <TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-26T00:00:00+00:00 [running]> on host dcbd1801a890
[2024-07-16T07:54:19.128+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_remote_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-26T00:00:00+00:00'
[2024-07-16T07:54:19.131+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/run_notebook.py", line 16, in execute_remote_notebook
    update_notebook_format('/tmp/input_notebook.ipynb')
  File "/opt/airflow/dags/run_notebook.py", line 52, in update_notebook_format
    nb = nbformat.read(f, as_version=4)
  File "/home/airflow/.local/lib/python3.7/site-packages/nbformat/__init__.py", line 171, in read
    return reads(buf, as_version, capture_validation_error, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/nbformat/__init__.py", line 91, in reads
    nb = convert(nb, as_version)
  File "/home/airflow/.local/lib/python3.7/site-packages/nbformat/converter.py", line 62, in convert
    raise ValidationError(msg) from None
jsonschema.exceptions.ValidationError: Notebook could not be converted from version 1 to version 2 because it's missing a key: cells
[2024-07-16T07:54:19.143+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=run_remote_jupyter_notebook, task_id=run_notebook, execution_date=20240426T000000, start_date=20240716T075418, end_date=20240716T075419
[2024-07-16T07:54:19.164+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1414 for task run_notebook (Notebook could not be converted from version 1 to version 2 because it's missing a key: cells; 2082)
[2024-07-16T07:54:19.204+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-16T07:54:19.234+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T07:00:30.720+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-26T00:00:00+00:00 [queued]>
[2024-07-18T07:00:30.735+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-26T00:00:00+00:00 [queued]>
[2024-07-18T07:00:30.736+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-18T07:00:30.780+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2024-04-26 00:00:00+00:00
[2024-07-18T07:00:30.802+0000] {standard_task_runner.py:57} INFO - Started process 24688 to run task
[2024-07-18T07:00:30.819+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_remote_jupyter_notebook', 'run_notebook', 'scheduled__2024-04-26T00:00:00+00:00', '--job-id', '484', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmpmc1yw1l1']
[2024-07-18T07:00:30.825+0000] {standard_task_runner.py:85} INFO - Job 484: Subtask run_notebook
[2024-07-18T07:00:30.963+0000] {task_command.py:410} INFO - Running <TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2024-04-26T00:00:00+00:00 [running]> on host 6c8b3b9a6388
[2024-07-18T07:00:31.173+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_remote_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-26T00:00:00+00:00'
[2024-07-18T07:00:34.925+0000] {logging_mixin.py:149} INFO - Notebook executed and updated successfully on the server.
[2024-07-18T07:00:34.926+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-07-18T07:00:34.941+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=run_remote_jupyter_notebook, task_id=run_notebook, execution_date=20240426T000000, start_date=20240718T070030, end_date=20240718T070034
[2024-07-18T07:00:35.002+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-18T07:00:35.023+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
