[2024-07-15T11:09:40.464+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-06-26T00:00:00+00:00 [queued]>
[2024-07-15T11:09:40.480+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-06-26T00:00:00+00:00 [queued]>
[2024-07-15T11:09:40.481+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-07-15T11:09:40.505+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2023-06-26 00:00:00+00:00
[2024-07-15T11:09:40.518+0000] {standard_task_runner.py:57} INFO - Started process 1493 to run task
[2024-07-15T11:09:40.523+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_remote_jupyter_notebook', 'run_notebook', 'scheduled__2023-06-26T00:00:00+00:00', '--job-id', '818', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmpcrhsauq4']
[2024-07-15T11:09:40.526+0000] {standard_task_runner.py:85} INFO - Job 818: Subtask run_notebook
[2024-07-15T11:09:40.591+0000] {task_command.py:410} INFO - Running <TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-06-26T00:00:00+00:00 [running]> on host 9f73ee97e438
[2024-07-15T11:09:41.424+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_remote_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2023-06-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-26T00:00:00+00:00'
[2024-07-15T11:09:41.429+0000] {run_notebook.py:14} INFO - Attempting to connect to http://host.docker.internal:8888/notebooks/Notebooks/notebook.ipynb?token=3b56a766afdef52d8fa1fa30bde9f5e0755d377370514cb6
[2024-07-15T11:09:41.488+0000] {run_notebook.py:39} ERROR - Error connecting to notebook: Expecting value: line 1 column 1 (char 0)
[2024-07-15T11:09:41.489+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/run_notebook.py", line 22, in execute_remote_notebook
    notebook_content = response.json()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-15T11:09:41.526+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=run_remote_jupyter_notebook, task_id=run_notebook, execution_date=20230626T000000, start_date=20240715T110940, end_date=20240715T110941
[2024-07-15T11:09:41.567+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 818 for task run_notebook (Expecting value: line 1 column 1 (char 0); 1493)
[2024-07-15T11:09:41.622+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-15T11:09:41.653+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
